version: '2'


services:
  app:
    container_name: app
    build: .
    ports:
      - '5002:5002'
    links:
      - elasticsearch
    depends_on:
      - elasticsearch

  elasticsearch:
    image: 'bitnami/elasticsearch:6'
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
