version: '2'

services:
  app:
    container_name: app
    build: .
    ports:
      - '5002:5002'
    depends_on:
      - elasticsearch
    networks:
      - mynetwork

  elasticsearch:
    image: 'bitnami/elasticsearch:7.7.1'
    container_name: elastic
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
